services:
  sheet-music-sync-backend:
    container_name: sheet-music-sync-backend
    build:
      context: ../..
      dockerfile: services/sync_backend/Dockerfile
    image: ghcr.io/basmulder03/sheet-music-sync-backend:dev
    ports:
      - '9090:9090'
    environment:
      SYNC_BACKEND_HOST: 0.0.0.0
      SYNC_BACKEND_PORT: 9090
      SYNC_BACKEND_DATA_DIR: /data
      SYNC_BACKEND_API_TOKEN: change-me
    volumes:
      - ./data:/data
    restart: unless-stopped
